FILE_NAME = "uncommitted/votes_test.jsonl"
DB_NAME = "warehouse.db"
DB_SCHEMA_NAME = "blog_analysis"
DB_TABLE_NAME = "votes"
VIEW_NAME = "outlier_weeks"
FULL_VIEW_NAME = f"{DB_SCHEMA_NAME}.{VIEW_NAME}"
DB_TABLE_FULL_NAME = f"{DB_SCHEMA_NAME}.{DB_TABLE_NAME}"